In [ ]:
import numpy as np
import pandas as pd

# Numpy sirve para trabajar con arreglos y operaciones matemáticas eficientes.
# Un arreglo es una estructura de datos que almacena elementos del mismo tipo en una secuencia contigua en memoria.

# Pandas es una biblioteca para manipulación y análisis de datos, especialmente con estructuras como DataFrames y Series.
# Una Serie es una estructura de datos unidimensional que puede contener datos de cualquier tipo (enteros, cadenas, etc.) y está etiquetada con un índice.
# Un DataFrame es una estructura de datos bidimensional similar a una tabla, que puede contener múltiples Series con diferentes tipos de datos y está etiquetada tanto por filas como por columnas.

lista_py = [[1,2,3],[4,5,6]]

# Creamos arreglo con numpy
arreglo_np = np.array(lista_py)
print(f"Arreglo numpy:\n{arreglo_np}")

# Inspección del arreglo
print(f"Forma (shape): {arreglo_np.shape}") # (filas, columnas)
print(f"Tipo de dato (dtype): {arreglo_np.dtype}") # tipo de los elementos
print(f"Número de dimensiones (ndim): {arreglo_np.ndim}") # Dimensiones del arreglo
print(f"Tamaño (size): {arreglo_np.size}") # Número total de elementos


Arreglo numpy:
[[1 2 3]
 [4 5 6]]
Forma (shape): (2, 3)
Tipo de dato (dtype): int64
Número de dimensiones (ndim): 2
Tamaño (size): 6
Tipo de objeto: <class 'numpy.ndarray'>
Contenido:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Conceptos base: Generadores de arrays

# np.arrange(): Crea un arreglo con una secuencia de números en un rango específico.
# (inicio, fin, paso)

arreglo_rango = np.arrange(0, 10, 2)
